import { createHash } from "node:crypto";
import { lstat, realpath } from "node:fs/promises";
import path from "node:path";
import type { HostTarget } from "./types.js";

export const GENERATED_PATHS = [
  "scripts/package-tauri.mjs",
  "scripts/package-tauri.test.mjs",
  "scripts/smoke-tauri-package.mjs",
  "scripts/smoke-tauri-package.test.mjs",
  "scripts/package-tauri.config.json",
  ".gg/commands/package-tauri.md",
] as const;

export const CONTENT_DIGEST_SENTINEL = "0".repeat(64);
export const TAURI_PACKAGE_MARKER = "@generated by ggcoder tauri-package";

export function sha256(value: string | Buffer): string {
  return createHash("sha256").update(value).digest("hex");
}

export function stableJson(value: unknown): string {
  if (value === null || typeof value !== "object") {
    const encoded = JSON.stringify(value);
    if (encoded === undefined) throw new TypeError("Value is not JSON-serializable");
    return encoded;
  }
  if (Array.isArray(value)) return `[${value.map(stableJson).join(",")}]`;
  const record = value as Record<string, unknown>;
  return `{${Object.keys(record)
    .sort()
    .filter((key) => record[key] !== undefined)
    .map((key) => `${JSON.stringify(key)}:${stableJson(record[key])}`)
    .join(",")}}`;
}

export function canonicalJson(value: unknown): string {
  return `${JSON.stringify(sortJson(value), null, 2)}\n`;
}

export function compareText(left: string, right: string): number {
  return left < right ? -1 : left > right ? 1 : 0;
}

function sortJson(value: unknown): unknown {
  if (value === null || typeof value !== "object") return value;
  if (Array.isArray(value)) return value.map(sortJson);
  return Object.fromEntries(
    Object.entries(value as Record<string, unknown>)
      .filter(([, item]) => item !== undefined)
      .sort(([left], [right]) => compareText(left, right))
      .map(([key, item]) => [key, sortJson(item)]),
  );
}

export function normalizeRepositoryPath(input: string): string {
  if (!input || input.includes("\0") || input.includes("\\") || path.posix.isAbsolute(input)) {
    throw new Error(`Path must be a non-empty repository-relative POSIX path: ${JSON.stringify(input)}`);
  }
  const normalized = path.posix.normalize(input);
  if (
    normalized === "." ||
    normalized === ".." ||
    normalized.startsWith("../") ||
    normalized !== input.replace(/^\.\//, "")
  ) {
    throw new Error(`Path escapes or is not normalized: ${JSON.stringify(input)}`);
  }
  return normalized;
}

export function relativeRepositoryPath(repositoryRoot: string, absolutePath: string): string {
  const relative = path.relative(repositoryRoot, absolutePath).split(path.sep).join("/");
  return normalizeRepositoryPath(relative);
}

export function containedPath(repositoryRoot: string, repositoryPath: string): string {
  const normalized = normalizeRepositoryPath(repositoryPath);
  const resolved = path.resolve(repositoryRoot, ...normalized.split("/"));
  const relative = path.relative(path.resolve(repositoryRoot), resolved);
  if (relative.startsWith("..") || path.isAbsolute(relative)) {
    throw new Error(`Path escapes repository: ${repositoryPath}`);
  }
  return resolved;
}

export async function canonicalRepositoryRoot(repositoryRoot: string): Promise<string> {
  const canonical = await realpath(repositoryRoot);
  const stat = await lstat(canonical);
  if (!stat.isDirectory()) throw new Error(`Repository root is not a directory: ${repositoryRoot}`);
  return canonical;
}

export async function rejectLinks(
  repositoryRoot: string,
  repositoryPath: string,
  allowMissingLeaf = false,
): Promise<string> {
  const normalized = normalizeRepositoryPath(repositoryPath);
  const segments = normalized.split("/");
  let current = path.resolve(repositoryRoot);
  for (let index = 0; index < segments.length; index += 1) {
    current = path.join(current, segments[index]!);
    try {
      const stat = await lstat(current);
      if (stat.isSymbolicLink()) throw new Error(`Symbolic links are not supported: ${repositoryPath}`);
    } catch (error) {
      if (
        allowMissingLeaf &&
        index === segments.length - 1 &&
        (error as NodeJS.ErrnoException).code === "ENOENT"
      ) {
        return current;
      }
      throw error;
    }
  }
  return current;
}

export function assertNoCaseCollisions(paths: Iterable<string>): void {
  const seen = new Map<string, string>();
  for (const candidate of paths) {
    const normalized = normalizeRepositoryPath(candidate);
    const key = normalized.toLocaleLowerCase("en-US");
    const previous = seen.get(key);
    if (previous && previous !== normalized) {
      throw new Error(`Case-colliding paths are unsupported: ${previous}, ${normalized}`);
    }
    seen.set(key, normalized);
  }
}

export function detectHostTarget(
  platform: NodeJS.Platform = process.platform,
  arch = process.arch,
): HostTarget {
  const triples: Record<string, string> = {
    "win32-x64": "x86_64-pc-windows-msvc",
    "win32-arm64": "aarch64-pc-windows-msvc",
    "darwin-x64": "x86_64-apple-darwin",
    "darwin-arm64": "aarch64-apple-darwin",
    "linux-x64": "x86_64-unknown-linux-gnu",
    "linux-arm64": "aarch64-unknown-linux-gnu",
  };
  const id = `${platform}-${arch}`;
  const rust_triple = triples[id];
  if (!rust_triple) throw new Error(`Unsupported host target: ${id}`);
  return { platform, arch, id, rust_triple };
}

export function normalizedContentSha256(content: string): string {
  const pattern = /(content_sha256["']?\s*[:=]\s*["']?)([a-f0-9]{64})/g;
  const matches = [...content.matchAll(pattern)];
  if (matches.length !== 1) throw new Error("Generated file must contain exactly one content digest");
  return sha256(content.replace(pattern, `$1${CONTENT_DIGEST_SENTINEL}`));
}
