import { cp, mkdir, mkdtemp, readFile, rm, writeFile } from "node:fs/promises";
import os from "node:os";
import path from "node:path";
import { afterEach, describe, expect, it } from "vitest";
import { discoverTauriPackages } from "./discover.js";
import { commitSupportSet } from "./ownership.js";
import { detectHostTarget, GENERATED_PATHS } from "./paths.js";
import { renderTauriSupport } from "./render.js";
import type { CalibrationBounds } from "./types.js";
import { verifyTauriPackage } from "./verify.js";

const fixture = path.join(import.meta.dirname, "__fixtures__", "valid");
const roots: string[] = [];

async function setup(invalidCalibration: "negative" | "fractional" | false = false): Promise<{ root: string; targetId: string }> {
  const root = await mkdtemp(path.join(os.tmpdir(), "gg-tauri-verify-"));
  roots.push(root);
  await cp(fixture, root, { recursive: true });
  const cli = path.join(root, "apps/desktop/node_modules/@tauri-apps/cli");
  await mkdir(cli, { recursive: true });
  await writeFile(path.join(cli, "package.json"), `${JSON.stringify({ version: "2.11.2", bin: { tauri: "./tauri.js" } }, null, 2)}\n`);
  await writeFile(path.join(cli, "tauri.js"), "module.exports = {};\n");
  const host = detectHostTarget();
  const binaries = path.join(root, "apps/desktop/src-tauri/binaries");
  await mkdir(binaries, { recursive: true });
  await writeFile(path.join(binaries, `helper-${host.rust_triple}${host.platform === "win32" ? ".exe" : ""}`), "sidecar\n");
  const discovery = await discoverTauriPackages(root);
  const target = discovery.targets[0]!;
  const calibration: CalibrationBounds | null = invalidCalibration
    ? {
        evidence_sha256: discovery.evidence_sha256,
        baseline_total_bytes: 1,
        maximum_total_bytes: invalidCalibration === "negative" ? -1 : 1,
        maximum_file_bytes: 1,
        role_counts: { app: invalidCalibration === "fractional" ? 1.5 : 1, bundle: 0 },
        role_maximum_bytes: { app: 1, bundle: 0 },
        required_paths: [],
        absolute_growth_bytes: 0,
        percentage_growth: 0,
      }
    : null;
  await commitSupportSet(root, renderTauriSupport(discovery, target, calibration));
  return { root, targetId: target.target_id };
}

afterEach(async () => {
  await Promise.all(roots.splice(0).map((root) => rm(root, { recursive: true, force: true })));
});

describe("verifyTauriPackage", () => {
  it("independently verifies exact templates, config, provenance, and target derivation", async () => {
    const value = await setup();
    await expect(verifyTauriPackage(value.root)).resolves.toMatchObject({
      ok: true,
      target_id: value.targetId,
      errors: [],
    });
  });

  it("rejects stale source evidence", async () => {
    const value = await setup();
    await writeFile(path.join(value.root, "apps/desktop/src-tauri/resources/data.txt"), "changed\n");
    const result = await verifyTauriPackage(value.root);
    expect(result.ok).toBe(false);
    expect(result.errors).toContain("Repository evidence digest is stale");
  });

  it("rejects manual edits to fixed generated bytes", async () => {
    const value = await setup();
    const script = path.join(value.root, GENERATED_PATHS[0]);
    await writeFile(script, `${await readFile(script, "utf8")}manual\n`);
    const result = await verifyTauriPackage(value.root);
    expect(result.ok).toBe(false);
    expect(result.errors.join("\n")).toContain("content digest mismatch");
  });

  it("rejects non-finite or negative calibration bounds", async () => {
    const value = await setup("negative");
    const result = await verifyTauriPackage(value.root);
    expect(result.ok).toBe(false);
    expect(result.errors.join("\n")).toContain("calibration.maximum_total_bytes must be finite and non-negative");
  });

  it("rejects fractional calibrated artifact counts", async () => {
    const value = await setup("fractional");
    const result = await verifyTauriPackage(value.root);
    expect(result.ok).toBe(false);
    expect(result.errors.join("\n")).toContain("calibration.role_counts.app must be a non-negative safe integer");
  });

  it("does not change generated files", async () => {
    const value = await setup();
    const before = await Promise.all(GENERATED_PATHS.map((item) => readFile(path.join(value.root, item))));
    await verifyTauriPackage(value.root);
    const after = await Promise.all(GENERATED_PATHS.map((item) => readFile(path.join(value.root, item))));
    expect(after).toEqual(before);
  });
});
