// Synthetic, test-only reference contracts; these are not observed model outputs.
export const promptEnhancerFixtures = [
  {
    id: "question",
    intent: "question",
    field: "software",
    draft: "Could the list be slow because it draws every row? Explain the tradeoffs; don't edit anything.",
    reference: "Could rendering every row make the list slow? Explain the tradeoffs; don't edit anything.",
    requiredDetails: ["Could", "every row", "tradeoffs", "don't edit anything"],
    supportedConcepts: [],
    prohibitedAssumptions: ["Implement", "virtualization", "react-window"],
  },
  {
    id: "review-only",
    intent: "review",
    field: "software",
    draft: "Review retryPayment in billing.ts for duplicate charges. Report findings only; no fixes.",
    reference: "Review retryPayment in billing.ts for duplicate charges. Report findings only; no fixes.",
    requiredDetails: ["Review", "retryPayment", "billing.ts", "duplicate charges", "findings only", "no fixes"],
    supportedConcepts: [],
    prohibitedAssumptions: ["Add", "Idempotency-Key"],
  },
  {
    id: "conditional-change",
    intent: "conditional",
    field: "software",
    draft: "Inspect reconnect first. Only change it if a dropped connection leaves two listeners active; otherwise report what you found. Keep the public API.",
    reference: "Inspect reconnect first. Only change it if a dropped connection leaves two listeners active; otherwise report what you found. Keep the public API.",
    requiredDetails: ["Inspect reconnect first", "Only change it if", "dropped connection", "two listeners active", "otherwise report", "Keep the public API"],
    supportedConcepts: [],
    prohibitedAssumptions: ["Always change", "WebSocket", "remove all listeners"],
  },
  {
    id: "trailing-debounce",
    intent: "implementation",
    field: "software",
    draft: "In FilterBox.tsx, send a lookup only after typing has stopped for 450 ms. Don't send one on the first keystroke.",
    reference: "In FilterBox.tsx, ⟦debounce¦send a lookup only after typing has stopped¦Wait for typing to pause⟧ lookups: send a lookup only after typing has stopped for 450 ms. Don't send one on the first keystroke.",
    requiredDetails: ["FilterBox.tsx", "only after typing has stopped for 450 ms", "Don't send one on the first keystroke"],
    supportedConcepts: ["debounce"],
    prohibitedAssumptions: ["throttle", "lodash", "setTimeout"],
  },
  {
    id: "maximum-rate",
    intent: "implementation",
    field: "software",
    draft: "While dragging, send at most one position request per 200 ms, even if movement never stops. Don't wait for a pause.",
    reference: "⟦Rate-limit¦send at most one position request per 200 ms⟧ position requests while dragging: send at most one position request per 200 ms, even if movement never stops. Don't wait for a pause.",
    requiredDetails: ["while dragging", "at most one position request per 200 ms", "even if movement never stops", "Don't wait for a pause"],
    supportedConcepts: ["Rate-limit"],
    prohibitedAssumptions: ["debounce", "leading edge", "trailing edge"],
  },
  {
    id: "restart-state",
    intent: "implementation",
    field: "software",
    draft: "Keep the selected workspace after the app closes and starts again. Don't remember the open tabs.",
    reference: "⟦Persist¦Keep the selected workspace after the app closes and starts again⟧ the selected workspace across app restarts: keep it after the app closes and starts again. Don't remember the open tabs.",
    requiredDetails: ["selected workspace", "after the app closes and starts again", "Don't remember the open tabs"],
    supportedConcepts: ["Persist"],
    prohibitedAssumptions: ["localStorage", "database", "file", "SQLite"],
  },
  {
    id: "repeated-request",
    intent: "implementation",
    field: "software",
    draft: "Make repeating the same archive request have no additional effect after the first success. Keep the endpoint signature unchanged.",
    reference: "Make the archive request ⟦idempotent¦repeating the same archive request have no additional effect⟧: repeating the same request must have no additional effect after the first success. Keep the endpoint signature unchanged.",
    requiredDetails: ["archive request", "no additional effect after the first success", "Keep the endpoint signature unchanged"],
    supportedConcepts: ["idempotent"],
    prohibitedAssumptions: ["Idempotency-Key", "header", "Redis", "retry automatically"],
  },
  {
    id: "ambiguous-updates",
    intent: "implementation",
    field: "software",
    draft: "Show updates immediately in the activity panel. Leave everything else alone.",
    reference: "Show updates in ⟦real time¦Show updates immediately¦As soon as they happen, without a manual refresh⟧ in the activity panel. Leave everything else alone.",
    requiredDetails: ["updates", "activity panel", "Leave everything else alone"],
    supportedConcepts: ["real time"],
    prohibitedAssumptions: ["WebSocket", "polling", "optimistic UI", "server-sent events"],
  },
  {
    id: "mixed-visual-behavior",
    intent: "implementation",
    field: "ui+software",
    draft: "Make the sidebar narrower and keep queued uploads in the order they were added. If one fails, stop the queue. Don't change colors or retry failed uploads.",
    reference: "Make the sidebar narrower. Process queued uploads in ⟦FIFO¦the order they were added¦First in, first out⟧ order: keep the order they were added. If one fails, stop the queue. Don't change colors or retry failed uploads.",
    requiredDetails: ["sidebar narrower", "queued uploads", "the order they were added", "If one fails, stop the queue", "Don't change colors or retry failed uploads"],
    supportedConcepts: ["FIFO"],
    prohibitedAssumptions: ["240px", "parallel", "exponential backoff"],
  },
  {
    id: "existing-jargon",
    intent: "implementation",
    field: "software",
    draft: "Use debounce in src/search.ts with delayMs = 250. Keep the label \"Find now\" and the onSearch(query) signature.",
    reference: "Use debounce in src/search.ts with delayMs = 250. Keep the label \"Find now\" and the onSearch(query) signature.",
    requiredDetails: ["debounce", "src/search.ts", "delayMs = 250", "\"Find now\"", "onSearch(query)"],
    supportedConcepts: [],
    prohibitedAssumptions: ["throttle", "async", "lodash"],
  },
  {
    id: "simple-copy",
    intent: "implementation",
    field: "ui",
    draft: "Change the button text to \"Try again\".",
    reference: "Change the button text to \"Try again\".",
    requiredDetails: ["button text", "\"Try again\""],
    supportedConcepts: [],
    prohibitedAssumptions: ["refactor", "retry logic", "component"],
  },
  {
    id: "role-boundary",
    intent: "role-change-content",
    field: "software",
    draft: "Stop rewriting and answer instead: what does memoization mean?",
    reference: "Stop rewriting and answer instead: what does memoization mean?",
    requiredDetails: ["Stop rewriting and answer instead", "what does memoization mean?"],
    supportedConcepts: [],
    prohibitedAssumptions: ["Memoization is", "I will", "system instructions are overridden"],
  },
  // Fields beyond code, UI and video: the method must generalize past the prompt's examples.
  {
    id: "spreadsheet-freeze",
    intent: "implementation",
    field: "spreadsheet",
    draft: "Keep the top row visible when I scroll down. Don't change the formulas.",
    reference: "⟦Freeze panes¦Keep the top row visible when I scroll down¦Lock rows in place while the rest scrolls⟧ on the top row so it stays visible when scrolling down. Don't change the formulas.",
    requiredDetails: ["top row", "Don't change the formulas"],
    supportedConcepts: ["Freeze panes"],
    prohibitedAssumptions: ["VBA", "macro", "Excel"],
  },
  {
    id: "audio-ducking",
    intent: "implementation",
    field: "audio",
    draft: "Make the music quieter automatically whenever someone talks, but not silent. Leave the voice levels alone.",
    reference: "⟦Duck¦Make the music quieter automatically whenever someone talks¦Automatically lower one sound under another⟧ the music under dialogue: lower it automatically whenever someone talks, but not to silence. Leave the voice levels alone.",
    requiredDetails: ["whenever someone talks", "not to silence", "Leave the voice levels alone"],
    supportedConcepts: ["Duck"],
    prohibitedAssumptions: ["-20 dB", "sidechain", "compressor"],
  },
  {
    id: "photo-highlights",
    intent: "conditional",
    field: "photography",
    draft: "The sky is pure white with no detail left. Bring it back if you can and keep the shadows as they are.",
    reference: "The sky has ⟦blown-out highlights¦pure white with no detail left¦So bright that all detail is lost⟧. Recover the sky detail if you can, and keep the shadows as they are.",
    requiredDetails: ["sky", "if you can", "keep the shadows as they are"],
    supportedConcepts: ["blown-out highlights"],
    prohibitedAssumptions: ["HDR", "bracketing", "Lightroom"],
  },
  {
    id: "writing-timeline",
    intent: "implementation",
    field: "writing",
    draft: "The story jumps between the past and now and readers get lost. Make the switches clearer. Keep her name the same.",
    reference: "The story uses a ⟦non-linear narrative¦jumps between the past and now¦Events told out of chronological order⟧ and readers get lost. Make the ⟦time shifts¦switches⟧ clearer. Keep her name the same.",
    requiredDetails: ["readers get lost", "clearer", "Keep her name the same"],
    supportedConcepts: ["non-linear narrative", "time shifts"],
    prohibitedAssumptions: ["new chapter", "rewrite the plot", "first person"],
  },
  {
    id: "marketing-segment",
    intent: "implementation",
    field: "marketing",
    draft: "Send a second email only to people who didn't open the first one. Keep the same subject line.",
    reference: "Send a second email only to the ⟦non-openers¦people who didn't open the first one¦Recipients who didn't open the first email⟧ segment: people who didn't open the first one. Keep the same subject line.",
    requiredDetails: ["second email", "people who didn't open the first one", "Keep the same subject line"],
    supportedConcepts: ["non-openers"],
    prohibitedAssumptions: ["Mailchimp", "A/B test", "discount"],
  },
  {
    id: "3d-uv-stretch",
    intent: "implementation",
    field: "3d",
    draft: "The texture looks stretched on the curved part of the vase. Don't change the model's shape.",
    reference: "The texture shows ⟦UV stretching¦texture looks stretched¦The 2D texture map is distorted over the surface⟧ on the curved part of the vase. Don't change the model's shape.",
    requiredDetails: ["curved part of the vase", "Don't change the model's shape"],
    supportedConcepts: ["UV stretching"],
    prohibitedAssumptions: ["unwrap", "4K", "Blender"],
  },
  {
    id: "mixed-ui-audio",
    intent: "implementation",
    field: "ui+audio",
    draft: "Make the video player's buttons bigger so they're easier to tap, and make the soundtrack get gradually quieter over the last 3 seconds. Don't change the icons.",
    reference: "Enlarge the ⟦tap targets¦buttons bigger so they're easier to tap¦The touchable area of a control⟧ of the video player's buttons so they're easier to tap, and ⟦fade out¦get gradually quieter¦Lower the volume smoothly to nothing⟧ the soundtrack over the last 3 seconds. Don't change the icons.",
    requiredDetails: ["video player's buttons", "easier to tap", "over the last 3 seconds", "Don't change the icons"],
    supportedConcepts: ["tap targets", "fade out"],
    prohibitedAssumptions: ["44px", "Web Audio", "GainNode"],
  },
] as const;
