import { readFile } from "node:fs/promises";
import { z } from "zod";
import type { AgentTool } from "@kenkaiiii/gg-agent";
import { discoverTauriPackages } from "../core/tauri-package/discover.js";
import { commitSupportSet } from "../core/tauri-package/ownership.js";
import { containedPath, stableJson } from "../core/tauri-package/paths.js";
import { renderTauriSupport } from "../core/tauri-package/render.js";
import type { CalibrationBounds } from "../core/tauri-package/types.js";
import { verifyTauriPackage } from "../core/tauri-package/verify.js";
import { executeForegroundCommand, renderBashOutput } from "./bash.js";
import { localOperations, type ToolOperations } from "./operations.js";
import type { ProcessManager } from "../core/process-manager.js";
import { isPlanModeActive, planModeRestriction } from "../core/runtime-mode.js";
import { prepareSandboxLaunch, type SandboxPolicy } from "../core/sandbox.js";

export const TauriPackageParams = z
  .object({
    action: z.enum(["inspect", "setup", "calibrate", "package", "verify"]),
    target_id: z.string().min(1).optional(),
    evidence_sha256: z.string().regex(/^[a-f0-9]{64}$/).optional(),
  })
  .strict()
  .superRefine((value, context) => {
    if (value.action !== "inspect" && !value.target_id) {
      context.addIssue({ code: "custom", path: ["target_id"], message: "target_id is required" });
    }
    if (value.action === "setup" && !value.evidence_sha256) {
      context.addIssue({
        code: "custom",
        path: ["evidence_sha256"],
        message: "evidence_sha256 from inspect is required for setup",
      });
    }
  });

export interface TauriPackageToolOptions {
  operations?: ToolOperations;
  planModeRef?: { current: boolean };
  onPreFileMutation?: (absolutePath: string) => Promise<void> | void;
  onFileMutated?: (absolutePath: string) => Promise<void> | void;
  getSandboxPolicy?: () => SandboxPolicy;
}

export function createTauriPackageTool(
  cwd: string,
  processManager: ProcessManager,
  options: TauriPackageToolOptions = {},
): AgentTool<typeof TauriPackageParams> {
  const operations = options.operations ?? localOperations;
  return {
    name: "tauri_package",
    description:
      "Deterministically inspect, set up, calibrate, package, or verify one supported host-native Tauri v2 JSON application. " +
      "Repository discovery, generated bytes, exact process argv, evidence checks, and validation outcomes are owned by reviewed code.",
    parameters: TauriPackageParams,
    executionMode: "sequential",
    async execute(input, context) {
      if (operations !== localOperations) {
        return "Error: tauri_package supports only local ToolOperations in this version.";
      }
      const mutating = input.action === "setup" || input.action === "calibrate" || input.action === "package";
      if (mutating && isPlanModeActive(options.planModeRef)) return planModeRestriction("tauri_package");

      try {
        if (input.action === "inspect") {
          const result = await discoverTauriPackages(cwd);
          return stableJson({
            action: "inspect",
            evidence_sha256: result.evidence_sha256,
            issues: result.evidence.issues,
            summary: result.summary,
            targets: result.targets.map((target) => ({
              target_id: target.target_id,
              package_root: target.package_root,
              product_name: target.product_name,
              host: target.host,
            })),
          });
        }

        const targetId = input.target_id!;
        if (input.action === "setup") {
          const discovery = await discoverTauriPackages(cwd);
          if (discovery.evidence_sha256 !== input.evidence_sha256) {
            return stableJson({
              action: "setup",
              changed: false,
              error: "stale-evidence",
              expected: input.evidence_sha256,
              actual: discovery.evidence_sha256,
              summary: "Repository evidence changed after inspect; no files were written.",
            });
          }
          const target = discovery.targets.find((candidate) => candidate.target_id === targetId);
          if (!target) {
            return stableJson({
              action: "setup",
              changed: false,
              error: "unknown-target",
              target_id: targetId,
              available_target_ids: discovery.targets.map((candidate) => candidate.target_id),
            });
          }
          const existing = await verifyTauriPackage(cwd);
          let calibration: CalibrationBounds | null = null;
          if (
            existing.ok &&
            existing.target_id === targetId &&
            existing.evidence_sha256 === discovery.evidence_sha256
          ) {
            const config = JSON.parse(
              await readFile(containedPath(cwd, "scripts/package-tauri.config.json"), "utf8"),
            ) as { calibration: CalibrationBounds | null };
            calibration = config.calibration;
          }
          const rendered = renderTauriSupport(discovery, target, calibration);
          const committed = await commitSupportSet(cwd, rendered, {
            revalidate: async () => {
              const current = await discoverTauriPackages(cwd);
              if (current.evidence_sha256 !== discovery.evidence_sha256) {
                throw new Error("Repository evidence became stale immediately before commit");
              }
            },
            onPreMutation: (repositoryPath) =>
              options.onPreFileMutation?.(containedPath(cwd, repositoryPath)),
            onCommitted: (repositoryPath) =>
              options.onFileMutated?.(containedPath(cwd, repositoryPath)),
          });
          const verification = await verifyTauriPackage(cwd);
          return stableJson({
            action: "setup",
            changed: committed.changed,
            paths: committed.paths,
            target_id: targetId,
            evidence_sha256: discovery.evidence_sha256,
            verification,
          });
        }

        if (input.action === "verify") {
          const verification = await verifyTauriPackage(cwd);
          if (verification.target_id && verification.target_id !== targetId) {
            return stableJson({
              action: "verify",
              ok: false,
              errors: [`Configured target ${verification.target_id} does not match ${targetId}`],
            });
          }
          return stableJson({ action: "verify", ...verification });
        }

        const verification = await verifyTauriPackage(cwd);
        if (!verification.ok || verification.target_id !== targetId) {
          return stableJson({
            action: input.action,
            launched: false,
            error: "generated-set-verification-failed",
            verification,
          });
        }
        const configPath = containedPath(cwd, "scripts/package-tauri.config.json");
        if (input.action === "calibrate") await options.onPreFileMutation?.(configPath);
        const args = [containedPath(cwd, "scripts/package-tauri.mjs")];
        if (input.action === "calibrate") args.push("--calibrate");
        args.push("--target", targetId);
        const policy = options.getSandboxPolicy?.() ?? { mode: "off", allowedDomains: [] };
        const launch = await prepareSandboxLaunch(
          { file: process.execPath, args, isCmdFallback: false },
          cwd,
          policy,
        );
        const execution = await executeForegroundCommand({
          command: `tauri_package ${input.action}`,
          cwd,
          timeoutMs: 30 * 60 * 1000,
          signal: context.signal,
          ops: operations,
          processManager,
          launch,
        });
        const output = await renderBashOutput(execution.rawOutput);
        const succeeded = execution.outcome.reason === "completed" && execution.outcome.exitCode === 0;
        if (succeeded && input.action === "calibrate") await options.onFileMutated?.(configPath);
        const after = succeeded ? await verifyTauriPackage(cwd) : undefined;
        return stableJson({
          action: input.action,
          launched: true,
          succeeded,
          exit_code: execution.outcome.exitCode,
          reason: execution.outcome.reason,
          output,
          verification: after,
        });
      } catch (error) {
        return stableJson({
          action: input.action,
          error: error instanceof Error ? error.message : String(error),
        });
      }
    },
  };
}
