import { describe, expect, it, vi } from "vitest";
import { PROMPT_COMMANDS } from "./prompt-commands.js";

describe("prompt commands", () => {
  it("no longer defines the /goal command", () => {
    expect(PROMPT_COMMANDS.find((command) => command.name === "goal")).toBeUndefined();
    expect(PROMPT_COMMANDS.find((command) => command.aliases.includes("g"))).toBeUndefined();
  });

  it("hands setup/bullet-proof fixes off to the tasks tool, not a Goal", () => {
    const setup = PROMPT_COMMANDS.find((command) => command.name === "setup");
    const bulletProof = PROMPT_COMMANDS.find((command) => command.name === "bullet-proof");

    expect(setup?.prompt).toContain("`tasks` tool");
    expect(setup?.prompt).toContain("Press Ctrl+T to open the task list");
    expect(setup?.prompt).not.toContain("Create a Goal");
    expect(setup?.prompt).not.toContain("Press CTRL + G");
    expect(bulletProof?.prompt).toContain("`tasks` tool");
    expect(bulletProof?.prompt).toContain("Press Ctrl+T to open the task list");
    expect(bulletProof?.prompt).not.toContain("Create a Goal");
    expect(bulletProof?.prompt).not.toContain("Press CTRL + G");
  });

  it("keeps /setup's six-category audit, empty-project gate, and task handoff", () => {
    const setup = PROMPT_COMMANDS.find((command) => command.name === "setup");
    const prompt = setup?.prompt ?? "";

    expect(setup).toBeDefined();
    expect(prompt).toContain("### 1. Project hygiene");
    expect(prompt).toContain("### 2. Toolchain version pinning");
    expect(prompt).toContain("### 3. Code quality tooling");
    expect(prompt).toContain("### 4. Verify pipeline");
    expect(prompt).toContain("### 5. Style pack alignment");
    expect(prompt).toContain("### 6. Documentation hygiene");
    expect(prompt).toContain("Empty project — nothing to audit");
    expect(prompt).toContain("then stop");
    expect(prompt).toContain("A) Add tasks for all [GAP] items");
    expect(prompt).toContain("`tasks` tool");
  });

  it("limits /setup automatic writes to the three marked generated-support files", () => {
    const prompt = PROMPT_COMMANDS.find((command) => command.name === "setup")?.prompt ?? "";
    const supportSet = prompt.slice(
      prompt.indexOf("For every non-empty project"),
      prompt.indexOf("### Ownership and conflict handling"),
    );
    const supportPaths = [...supportSet.matchAll(/- `([^`]+)` —/g)].map((match) => match[1]);

    expect(supportPaths).toEqual([
      "scripts/audit-generated.mjs",
      "scripts/audit-generated.test.mjs",
      ".gg/commands/cleanup.md",
    ]);
    expect(prompt).toContain("Generated by GG Coder /setup generated-audit v1");
    expect(prompt).toContain("Read all three destinations first");
    expect(prompt).toContain("preserve it byte-for-byte");
    expect(prompt).toContain("do not partially create or replace");
    expect(prompt).toContain("These are the only files this command may edit automatically");
    expect(prompt).toContain("never create project-local scratch/output files");
    expect(prompt).toContain("redirect to `NUL` or `/dev/null`");
    expect(prompt).toContain("compare it in memory");
    expect(prompt).toContain(
      "Dependencies, package scripts, manifests, ignore rules, product code, documentation",
    );
  });

  it("requires bounded evidence-led generated-target discovery", () => {
    const prompt = PROMPT_COMMANDS.find((command) => command.name === "setup")?.prompt ?? "";

    expect(prompt).toContain("root manifests, directly declared workspace manifests");
    expect(prompt).toContain("Do not crawl or grep source trees");
    expect(prompt).toContain("private candidate registry");
    expect(prompt).toContain("generation evidence");
    expect(prompt).toContain("never persist `packages/*/dist` or any glob");
    expect(prompt).toContain("git check-ignore --no-index -v -z --stdin");
    expect(prompt).toContain("force-added tracked descendants");
    expect(prompt).toContain("each literal path appears in exactly one stable target");
    expect(prompt).toContain("git ls-files -z -- <literal-path>");
    expect(prompt).toContain("README-only project has an empty target list");
    expect(prompt).toContain("never guess `dist`, `build`, cache, or dependency directories");
    expect(prompt).toContain("dynamic or ambiguous build config as unsupported");
    expect(prompt).toContain("rather than importing, executing, or guessing it");
  });

  it("specifies deterministic cross-stack generated fixtures and rerun proof", () => {
    const prompt = PROMPT_COMMANDS.find((command) => command.name === "setup")?.prompt ?? "";

    expect(prompt).toContain("Node fixtures: Vite and TypeScript");
    expect(prompt).toContain("Rust/Tauri fixtures");
    expect(prompt).toContain("Monorepo fixtures");
    expect(prompt).toContain("Unknown fixture: a README-only Git project");
    expect(prompt).toContain("node scripts/audit-generated.test.mjs");
    expect(prompt).toContain("An unchanged rerun must be byte-identical");
    expect(prompt).toContain("git status --short");
    expect(prompt).toContain("before/after in memory");
    expect(prompt).toContain("Windows and POSIX");
    expect(prompt).toContain("Immediately before reporting, run the complete fixture test");
    expect(prompt).toContain(
      "If any later change touches a support file, repeat this terminal gate",
    );
    expect(prompt).toContain("never report completion after a failed terminal run");
  });

  it("makes the generated audit physically read-only and deletion-proof", () => {
    const prompt = PROMPT_COMMANDS.find((command) => command.name === "setup")?.prompt ?? "";

    expect(prompt).toContain("--inspect");
    expect(prompt).toContain("present/missing, tracked/untracked, ignored/not-ignored");
    expect(prompt).toContain("Explicitly reject `--apply`, `--delete`, `--clean`, `--force`");
    expect(prompt).toContain("must not import or call filesystem mutators");
    expect(prompt).toContain("symbolic links, Windows junctions, nested `.git` directories");
    expect(prompt).toContain("`Refusing to audit ...` error");
    expect(prompt).toContain("`execFile` with `shell: false`");
    expect(prompt).toContain("snapshot each complete fixture tree before and after");
    expect(prompt).toContain(
      "Neither setup nor the generated cleanup command may delete or alter audited artifacts",
    );
  });

  it("points at the app's Tasks button / New Session instead of CLI keybinds when run under gg-app", async () => {
    const previous = process.env.GG_APP_PORT;
    process.env.GG_APP_PORT = "0";
    vi.resetModules();
    try {
      const { PROMPT_COMMANDS: appPromptCommands } = await import("./prompt-commands.js");
      const setup = appPromptCommands.find((command) => command.name === "setup");
      const bulletProof = appPromptCommands.find((command) => command.name === "bullet-proof");
      const init = appPromptCommands.find((command) => command.name === "init");

      expect(setup?.prompt).toContain('Click the "Tasks" button');
      expect(setup?.prompt).not.toContain("Ctrl+T");
      expect(bulletProof?.prompt).toContain('Click the "Tasks" button');
      expect(bulletProof?.prompt).not.toContain("Ctrl+T");
      expect(init?.prompt).toContain("New Session");
      expect(init?.prompt).toContain('click "+ New"');
      expect(init?.prompt).not.toContain("restart ggcoder");
      expect(init?.prompt).not.toContain("/quit");
    } finally {
      if (previous === undefined) delete process.env.GG_APP_PORT;
      else process.env.GG_APP_PORT = previous;
      vi.resetModules();
    }
  });

  it("removes retired prompt-template commands", () => {
    const removedCommandNames = [
      "scan",
      "verify",
      "source",
      "simplify",
      "batch",
      "research",
      "setup-lint",
      `setup-${"tests"}`,
      "setup-update",
    ];
    const removedAliases = ["depcheck", "depsource"];

    for (const name of removedCommandNames) {
      expect(PROMPT_COMMANDS.find((command) => command.name === name)).toBeUndefined();
    }
    for (const alias of removedAliases) {
      expect(PROMPT_COMMANDS.find((command) => command.aliases.includes(alias))).toBeUndefined();
    }
  });

  it("defines /expand as a fresh, repo-validated, feature-first plan-mode command", () => {
    const expand = PROMPT_COMMANDS.find((command) => command.name === "expand");

    expect(expand).toBeDefined();
    expect(expand?.prompt).toContain("Spawn exactly 5 sub-agents in parallel");
    expect(expand?.prompt).toContain("updated within the last 6 months");
    expect(expand?.prompt).toContain("validate it yourself before reporting");
    expect(expand?.prompt).toContain("The table must have exactly 3 columns");
    expect(expand?.prompt).toContain("Do not start implementing until the user chooses");
    expect(expand?.prompt).toContain("A) Build all of these features in plan mode");
    expect(expand?.prompt).toContain("B) Build only the top priority ones in plan mode");
    expect(expand?.prompt).toContain("C) Other");
    expect(expand?.prompt).toContain("call the enter_plan tool");
    expect(expand?.prompt).toContain("call exit_plan with the plan path");
    expect(expand?.prompt).not.toContain("Create a Goal");
    expect(expand?.prompt).not.toContain("planning-only Goal tasks");
  });

  it("keeps /init focused on project-specific CLAUDE.md content", () => {
    const init = PROMPT_COMMANDS.find((command) => command.name === "init");

    expect(init).toBeDefined();
    expect(init?.prompt).toContain("project-specific context only");
    expect(init?.prompt).toContain("Do NOT add generic agent behavior");
    expect(init?.prompt).toContain("Remove generic guidance");
    expect(init?.prompt).toContain("Never add guidance that requires running checks");
    expect(init?.prompt).toContain("mandatory after-every-edit requirements");
    expect(init?.prompt).toContain("After editing ANY file");
    expect(init?.prompt).toContain(
      "Do not duplicate language style packs, generic verification rules",
    );
    expect(init?.prompt).toContain("Do NOT embed generated symbol maps");
    expect(init?.prompt).toContain("auto-generated project inventories");
    expect(init?.prompt).toContain("CLAUDE.md must remain durable, agent-focused project context");
    expect(init?.prompt).not.toContain("human-authored");
    expect(init?.prompt).not.toContain("one file per component");
    expect(init?.prompt).not.toContain("single responsibility");
    expect(init?.prompt).not.toContain("zero-tolerance code quality checks");
    expect(init?.prompt).not.toContain("run full quality suite after every edit");
  });
});
