// Generated by GG Coder /setup generated-audit v1
import assert from "node:assert/strict";
import { execFile } from "node:child_process";
import { existsSync } from "node:fs";
import {
  copyFile,
  lstat,
  mkdtemp,
  mkdir,
  readFile,
  readdir,
  readlink,
  rm,
  symlink,
  writeFile,
} from "node:fs/promises";
import { tmpdir } from "node:os";
import { dirname, join, relative } from "node:path";
import test from "node:test";
import { promisify } from "node:util";

import {
  PROTECTED_RELATIVE_PATHS,
  assertProtectedPathsExcluded,
  auditGenerated,
  discoverGenerated,
  inspectGenerated,
  parseArgs,
  renderCleanupMarkdown,
} from "./audit-generated.mjs";

const execFileAsync = promisify(execFile);
const marker = "Generated by GG Coder /setup generated-audit v1";

async function withTempRepo(run) {
  const repoRoot = await mkdtemp(join(tmpdir(), "gg-audit-generated-"));
  await execFileAsync("git", ["init", "-q"], { cwd: repoRoot });
  try {
    await run(repoRoot);
  } finally {
    await rm(repoRoot, { recursive: true, force: true });
  }
}

async function writeJson(path, value) {
  await mkdir(dirname(path), { recursive: true });
  await writeFile(path, `${JSON.stringify(value, null, 2)}\n`);
}

async function writeWorkspace(repoRoot, patterns) {
  await writeJson(join(repoRoot, "package.json"), { private: true });
  await writeFile(
    join(repoRoot, "pnpm-workspace.yaml"),
    `packages:\n${patterns.map((pattern) => `  - "${pattern}"`).join("\n")}\n`,
  );
}

async function snapshotFixtureTree(repoRoot) {
  const snapshot = [];
  async function visit(directory) {
    const entries = await readdir(directory, { withFileTypes: true });
    entries.sort((left, right) => (left.name < right.name ? -1 : left.name > right.name ? 1 : 0));
    for (const entry of entries) {
      const absolutePath = join(directory, entry.name);
      const path = relative(repoRoot, absolutePath).replaceAll("\\", "/");
      const stat = await lstat(absolutePath);
      if (stat.isSymbolicLink()) {
        snapshot.push({ path, type: "link", mode: stat.mode, target: await readlink(absolutePath) });
      } else if (stat.isDirectory()) {
        snapshot.push({ path, type: "directory", mode: stat.mode });
        await visit(absolutePath);
      } else if (stat.isFile()) {
        snapshot.push({
          path,
          type: "file",
          mode: stat.mode,
          content: (await readFile(absolutePath)).toString("base64"),
        });
      } else {
        snapshot.push({ path, type: "other", mode: stat.mode });
      }
    }
  }
  await visit(repoRoot);
  return snapshot;
}

async function captureAudit(repoRoot, target) {
  const before = await snapshotFixtureTree(repoRoot);
  const messages = [];
  try {
    await auditGenerated({ repoRoot, target, log: (line) => messages.push(line) });
    return messages;
  } finally {
    assert.deepEqual(
      await snapshotFixtureTree(repoRoot),
      before,
      `audit ${target} mutated the fixture tree`,
    );
  }
}

async function createDirectoryLink(target, link) {
  await symlink(target, link, process.platform === "win32" ? "junction" : "dir");
}

function target(inspection, id) {
  return inspection.targets.find((candidate) => candidate.id === id);
}

function artifactPaths(inspection, id) {
  return target(inspection, id)?.artifacts.map((item) => item.path) ?? [];
}

test("all generated support files carry the ownership marker", async () => {
  const files = [
    new URL("./audit-generated.mjs", import.meta.url),
    new URL("./audit-generated.test.mjs", import.meta.url),
    new URL("../.gg/commands/cleanup.md", import.meta.url),
  ];
  for (const file of files) assert.match(await readFile(file, "utf8"), new RegExp(marker));
});

test("parseArgs exposes inspect and exactly one target while rejecting action flags", () => {
  assert.deepEqual(parseArgs(["--inspect"]), { inspect: true });
  assert.deepEqual(parseArgs(["--", "web"]), { target: "web" });
  assert.throws(() => parseArgs(["web", "tauri"]), /exactly one audit target/i);
  for (const option of ["--apply", "--delete", "--clean", "--force", "--unknown"]) {
    assert.throws(() => parseArgs(["web", option]), /Unknown option/);
  }
});

test("Node discovery uses Vite and package-entry evidence without conventional guesses", async () => {
  await withTempRepo(async (repoRoot) => {
    await writeWorkspace(repoRoot, ["apps/*", "packages/*"]);
    await writeJson(join(repoRoot, "apps", "web", "package.json"), {
      name: "web",
      scripts: { build: "tsc && vite build" },
    });
    await writeJson(join(repoRoot, "packages", "library", "package.json"), {
      name: "library",
      scripts: { build: "tsc" },
      exports: { ".": { import: "./dist/index.js", types: "./dist/index.d.ts" } },
    });
    await writeJson(join(repoRoot, "packages", "unrelated", "package.json"), {
      name: "unrelated",
      scripts: { test: "node test.mjs" },
    });

    const inspection = await inspectGenerated({ repoRoot });
    assert.deepEqual(artifactPaths(inspection, "web"), ["apps/web/dist"]);
    assert.deepEqual(artifactPaths(inspection, "packages"), ["packages/library/dist"]);
    assert.equal(JSON.stringify(inspection).includes("packages/unrelated/dist"), false);
    assert.equal(inspection.cleanupMarkdown.includes("*"), false);
    assert.equal(renderCleanupMarkdown(inspection), inspection.cleanupMarkdown);
  });
});

test("Rust/Tauri discovery honors a literal Cargo target-dir and evidenced outputs", async () => {
  await withTempRepo(async (repoRoot) => {
    await writeWorkspace(repoRoot, ["desktop"]);
    await writeJson(join(repoRoot, "desktop", "package.json"), {
      name: "desktop",
      scripts: { build: "vite build", "bundle:sidecar": "node scripts/bundle-sidecar.mjs" },
    });
    await mkdir(join(repoRoot, "desktop", "src-tauri"), { recursive: true });
    await mkdir(join(repoRoot, "desktop", ".cargo"), { recursive: true });
    await writeFile(join(repoRoot, "desktop", "src-tauri", "Cargo.toml"), "[package]\nname='app'\n");
    await writeFile(
      join(repoRoot, "desktop", "src-tauri", ".gitignore"),
      "/target/\n/gen/schemas\n/sidecar/\n",
    );
    await writeFile(join(repoRoot, "desktop", ".cargo", "config.toml"), 'target-dir = "cargo-out"\n');
    await writeJson(join(repoRoot, "desktop", "src-tauri", "tauri.conf.json"), {
      build: { frontendDist: "../dist" },
      bundle: { resources: ["sidecar/"] },
    });

    const inspection = await discoverGenerated({ repoRoot });
    assert.deepEqual(artifactPaths(inspection, "tauri"), ["desktop/cargo-out"]);
    assert.deepEqual(artifactPaths(inspection, "tauri-schemas"), [
      "desktop/src-tauri/gen/schemas",
    ]);
    assert.deepEqual(artifactPaths(inspection, "sidecar-deps"), ["desktop/src-tauri/sidecar"]);
    assert.deepEqual(artifactPaths(inspection, "web"), ["desktop/dist"]);
  });
});

test("monorepo discovery expands only direct declared buildable packages to literals", async () => {
  await withTempRepo(async (repoRoot) => {
    await writeWorkspace(repoRoot, ["packages/*"]);
    await writeJson(join(repoRoot, "packages", "zeta", "package.json"), {
      scripts: { build: "tsup" },
      main: "./build/index.js",
    });
    await writeJson(join(repoRoot, "packages", "alpha", "package.json"), {
      scripts: { build: "tsc" },
      types: "./dist/index.d.ts",
    });
    await writeJson(join(repoRoot, "packages", "no-build", "package.json"), {
      main: "./dist/index.js",
    });
    await writeJson(join(repoRoot, "undeclared", "hidden", "package.json"), {
      scripts: { build: "tsc" },
      main: "./dist/index.js",
    });

    const inspection = await discoverGenerated({ repoRoot });
    assert.deepEqual(artifactPaths(inspection, "packages"), [
      "packages/alpha/dist",
      "packages/zeta/build",
    ]);
    assert.equal(JSON.stringify(inspection).includes("*"), false);
    assert.equal(JSON.stringify(inspection).includes("no-build/dist"), false);
    assert.equal(JSON.stringify(inspection).includes("undeclared/hidden"), false);
  });
});

test("README-only repositories have stable empty inspection and cleanup output", async () => {
  await withTempRepo(async (repoRoot) => {
    await writeFile(join(repoRoot, "README.md"), "# Empty stack\n");
    const first = await inspectGenerated({ repoRoot });
    const second = await inspectGenerated({ repoRoot });
    assert.deepEqual(first, second);
    assert.deepEqual(first.targets, []);
    assert.match(first.cleanupMarkdown, /No generated-artifact targets were detected/);
    assert.doesNotMatch(first.cleanupMarkdown, /`(?:dist|build|target)`/);
  });
});

test("check-ignore --no-index preserves ignored state for a force-added descendant", async () => {
  await withTempRepo(async (repoRoot) => {
    await writeWorkspace(repoRoot, ["apps/web"]);
    await writeJson(join(repoRoot, "apps", "web", "package.json"), {
      scripts: { build: "vite build" },
    });
    await writeFile(join(repoRoot, ".gitignore"), "apps/web/dist/\n");
    const generated = join(repoRoot, "apps", "web", "dist", "index.html");
    await mkdir(dirname(generated), { recursive: true });
    await writeFile(generated, "generated");
    await execFileAsync("git", ["add", "-f", "--", "apps/web/dist/index.html"], { cwd: repoRoot });

    const messages = await captureAudit(repoRoot, "web");
    assert.ok(
      messages.some(
        (line) =>
          line.includes("path=apps/web/dist") &&
          line.includes("tracked=yes") &&
          line.includes("ignored=yes") &&
          line.includes("ignore-rule=.gitignore:1:apps/web/dist/"),
      ),
    );
  });
});

test("successful audits report missing and present literals deterministically without mutation", async () => {
  await withTempRepo(async (repoRoot) => {
    await writeWorkspace(repoRoot, ["apps/*"]);
    await writeJson(join(repoRoot, "apps", "one", "package.json"), {
      scripts: { build: "tsc" },
      main: "./dist/index.js",
    });
    await writeJson(join(repoRoot, "apps", "two", "package.json"), {
      scripts: { build: "tsc" },
      main: "./dist/index.js",
    });
    await writeFile(join(repoRoot, ".gitignore"), "apps/*/dist/\n");
    await mkdir(join(repoRoot, "apps", "one", "dist"), { recursive: true });
    await writeFile(join(repoRoot, "apps", "one", "dist", "index.js"), "generated");

    const first = await captureAudit(repoRoot, "packages");
    const second = await captureAudit(repoRoot, "packages");
    assert.deepEqual(first, second);
    assert.ok(first.some((line) => line.includes("path=apps/one/dist") && line.includes("present=yes")));
    assert.ok(first.some((line) => line.includes("path=apps/two/dist") && line.includes("present=no")));
  });
});

test("symlinks, junctions, and nested Git metadata are rejected without mutation", async () => {
  const outsideRoot = await mkdtemp(join(tmpdir(), "gg-audit-outside-"));
  try {
    await withTempRepo(async (repoRoot) => {
      await writeWorkspace(repoRoot, ["apps/web"]);
      await writeJson(join(repoRoot, "apps", "web", "package.json"), {
        scripts: { build: "vite build" },
      });
      await createDirectoryLink(outsideRoot, join(repoRoot, "apps", "web", "dist"));
      await assert.rejects(
        captureAudit(repoRoot, "web"),
        /Refusing to audit apps\/web\/dist: symbolic link or junction/,
      );
    });

    for (const gitShape of ["directory", "worktree file"]) {
      await withTempRepo(async (repoRoot) => {
        await writeWorkspace(repoRoot, ["apps/web"]);
        await writeJson(join(repoRoot, "apps", "web", "package.json"), {
          scripts: { build: "vite build" },
        });
        const nestedGit = join(repoRoot, "apps", "web", "dist", "nested", ".git");
        await mkdir(dirname(nestedGit), { recursive: true });
        if (gitShape === "directory") await mkdir(nestedGit);
        else await writeFile(nestedGit, "gitdir: elsewhere");
        await assert.rejects(
          captureAudit(repoRoot, "web"),
          /Refusing to audit apps\/web\/dist: nested Git repository metadata/,
        );
      });
    }
  } finally {
    await rm(outsideRoot, { recursive: true, force: true });
  }
});

test("spawned inspect and representative audit are deterministic and leave Git status unchanged", async () => {
  await withTempRepo(async (repoRoot) => {
    await writeWorkspace(repoRoot, ["apps/web"]);
    await writeJson(join(repoRoot, "apps", "web", "package.json"), {
      scripts: { build: "vite build" },
    });
    await writeFile(join(repoRoot, ".gitignore"), "apps/web/dist/\n");
    await mkdir(join(repoRoot, "scripts"), { recursive: true });
    await copyFile(
      new URL("./audit-generated.mjs", import.meta.url),
      join(repoRoot, "scripts", "audit-generated.mjs"),
    );

    const statusBefore = (await execFileAsync("git", ["status", "--short"], { cwd: repoRoot })).stdout;
    const inspectOne = (
      await execFileAsync(process.execPath, ["scripts/audit-generated.mjs", "--inspect"], {
        cwd: repoRoot,
      })
    ).stdout;
    const inspectTwo = (
      await execFileAsync(process.execPath, ["scripts/audit-generated.mjs", "--inspect"], {
        cwd: repoRoot,
      })
    ).stdout;
    assert.equal(inspectTwo, inspectOne);
    const parsed = JSON.parse(inspectOne);
    assert.equal(parsed.cleanupMarkdown, renderCleanupMarkdown(parsed));

    await execFileAsync(process.execPath, ["scripts/audit-generated.mjs", "web"], { cwd: repoRoot });
    const statusAfter = (await execFileAsync("git", ["status", "--short"], { cwd: repoRoot })).stdout;
    assert.equal(statusAfter, statusBefore);
  });
});

test("protected paths reject exact, descendant, and ancestor selections", () => {
  const repoRoot = process.cwd();
  for (const protectedPath of PROTECTED_RELATIVE_PATHS) {
    assert.throws(
      () => assertProtectedPathsExcluded(repoRoot, [join(repoRoot, protectedPath)]),
      /protected path/,
    );
  }
  assert.throws(
    () => assertProtectedPathsExcluded(repoRoot, [join(repoRoot, "gg-app", "src-tauri")]),
    /protected path/,
  );
});

test("production source has no filesystem mutators, mutating Git verbs, or action modes", async () => {
  const source = await readFile(new URL("./audit-generated.mjs", import.meta.url), "utf8");
  const mutators = [
    "appendFile",
    "chmod",
    "copyFile",
    "cp",
    "mkdir",
    "rename",
    "rm",
    "rmdir",
    "unlink",
    "writeFile",
  ];
  for (const mutator of mutators) {
    assert.doesNotMatch(source, new RegExp(`\\b${mutator}(?:Sync)?\\s*\\(`), `${mutator} call found`);
    assert.doesNotMatch(
      source,
      new RegExp(`import\\s*\\{[^}]*\\b${mutator}(?:Sync)?\\b[^}]*\\}\\s*from\\s*["']node:fs`),
      `${mutator} import found`,
    );
  }
  for (const verb of ["add", "clean", "checkout", "commit", "reset", "restore", "rm"]) {
    assert.doesNotMatch(source, new RegExp(`runGit\\([^\\n]+["']${verb}["']`));
  }
  assert.doesNotMatch(source, /case\s+["']--(?:apply|delete|clean|force)["']/);
});
