import { describe, expect, it } from "vitest";
import indexHtml from "../index.html?raw";
// The installer art pages are generated by build-pages.mjs (it renders the
// DMG background and NSIS sidebar/header PNGs); its page markup is the
// branding source of truth for every installer surface.
import installerPagesSource from "../installer/build-pages.mjs?raw";
import viteConfigSource from "../vite.config.ts?raw";
import tauriConfig from "../src-tauri/tauri.conf.json";
import updatePolicySource from "./update-policy.ts?raw";

describe("static Supah Coder branding", () => {
  it("brands the web document and installer surfaces", () => {
    expect(indexHtml).toContain("<title>Supah Coder</title>");
    expect(installerPagesSource).toContain("Drag Supah Coder into your Applications folder");
    // NSIS sidebar and header titles.
    expect(installerPagesSource.match(/>Supah Coder<\/div>/g)).toHaveLength(2);
    expect(installerPagesSource).toContain('"SUPAH CODER" ASCII banner');
    expect(installerPagesSource).not.toContain("GG Coder");
  });

  it("brands local fork build identity", () => {
    expect(viteConfigSource).toContain('const customBuildLabel = "Supah Coder Local Fork"');
  });

  it("pins native identity, installer hook, and official update discovery", () => {
    expect(tauriConfig.productName).toBe("GG Coder");
    expect(tauriConfig.identifier).toBe("com.ggcoder.app");
    expect(tauriConfig.bundle.windows.nsis.installerHooks).toBe("windows/nsis-hooks.nsh");
    expect(tauriConfig.plugins.updater.pubkey).not.toBe("");
    expect(tauriConfig.plugins.updater.endpoints).toEqual([
      "https://github.com/KenKaiii/gg-framework/releases/latest/download/latest.json",
    ]);
  });

  it("routes local-patched installation through the source updater", () => {
    expect(updatePolicySource).toContain(
      "await startLocalPatchedUpdate(sourceRoot, summarizeDecisions)",
    );
    expect(updatePolicySource).toContain('return "local-patched"');
  });
});
