export const PACKAGE_SCRIPT_TEMPLATE = String.raw`/*__GG_MARKER__*/
import { createHash, randomUUID } from "node:crypto";
import { spawn } from "node:child_process";
import { lstat, mkdir, readFile, readdir, realpath, rename, rm, stat, writeFile } from "node:fs/promises";
import os from "node:os";
import path from "node:path";
import { fileURLToPath } from "node:url";
import { smokeExecutable } from "./smoke-tauri-package.mjs";

const SUPPORT_PATHS = [
  "scripts/package-tauri.mjs",
  "scripts/package-tauri.test.mjs",
  "scripts/smoke-tauri-package.mjs",
  "scripts/smoke-tauri-package.test.mjs",
  "scripts/package-tauri.config.json",
  ".gg/commands/package-tauri.md",
];
const CONFIG_PATH = "scripts/package-tauri.config.json";
const OWNER_FILE = ".gg-tauri-owned.json";
const DIGEST_SENTINEL = "0".repeat(64);
const MARKER = /@generated by ggcoder tauri-package\s+template_version=(\d+)\s+template_sha256=([a-f0-9]{64})\s+content_sha256=([a-f0-9]{64})/;
const HASH = /^[a-f0-9]{64}$/;
const ROLES = new Set(["app", "bundle"]);
const SOURCE_ROLES = new Set(["root-package", "workspace-definition", "workspace-package", "lockfile", "cargo-manifest", "tauri-config", "tauri-cli-package", "tauri-cli-bin", "resource", "sidecar"]);

export function parsePackageArguments(args) {
  if (!Array.isArray(args)) throw new Error("Arguments must be an array");
  const result = { target: null, calibrate: false, verify: false };
  const seen = new Set();
  for (let index = 0; index < args.length; index += 1) {
    const flag = args[index];
    if (!new Set(["--target", "--calibrate", "--verify"]).has(flag)) throw new Error("Unknown argument: " + String(flag));
    if (seen.has(flag)) throw new Error("Duplicate argument: " + flag);
    seen.add(flag);
    if (flag === "--target") {
      const value = args[++index];
      if (typeof value !== "string" || !value || value.startsWith("-")) throw new Error("--target requires one value");
      result.target = value;
    } else if (flag === "--calibrate") result.calibrate = true;
    else result.verify = true;
  }
  if (!result.target) throw new Error("--target is required");
  if (result.calibrate && result.verify) throw new Error("Choose only --calibrate or --verify");
  return result;
}

function sha256(value) {
  return createHash("sha256").update(value).digest("hex");
}

function stable(value) {
  if (value === null || typeof value !== "object") {
    const encoded = JSON.stringify(value);
    if (encoded === undefined) throw new Error("Non-JSON value");
    return encoded;
  }
  if (Array.isArray(value)) return "[" + value.map(stable).join(",") + "]";
  return "{" + Object.keys(value).sort().filter((key) => value[key] !== undefined).map((key) => JSON.stringify(key) + ":" + stable(value[key])).join(",") + "}";
}

function compareText(left, right) {
  return left < right ? -1 : left > right ? 1 : 0;
}

function sorted(value) {
  if (value === null || typeof value !== "object") return value;
  if (Array.isArray(value)) return value.map(sorted);
  return Object.fromEntries(Object.entries(value).filter(([, item]) => item !== undefined).sort(([left], [right]) => compareText(left, right)).map(([key, item]) => [key, sorted(item)]));
}

function canonical(value) {
  return JSON.stringify(sorted(value), null, 2) + "\n";
}

function normalizedDigest(content) {
  const pattern = /(content_sha256["']?\s*[:=]\s*["']?)([a-f0-9]{64})/g;
  const matches = [...content.matchAll(pattern)];
  if (matches.length !== 1) throw new Error("Generated file must contain exactly one content digest");
  return sha256(content.replace(pattern, "$1" + DIGEST_SENTINEL));
}

function repositoryPath(value, field = "path") {
  if (typeof value !== "string" || !value || value.includes("\\") || value.includes("\0") || path.posix.isAbsolute(value) || /^[A-Za-z]:/.test(value)) throw new Error(field + " must be a repository-relative POSIX path");
  const normalized = path.posix.normalize(value);
  if (normalized === "." || normalized === ".." || normalized.startsWith("../") || normalized !== value.replace(/^\.\//, "")) throw new Error(field + " is not normalized or escapes the repository");
  return normalized;
}

function resolveRepository(root, value, field) {
  const relative = repositoryPath(value, field);
  const absolute = path.resolve(root, ...relative.split("/"));
  const back = path.relative(root, absolute);
  if (back.startsWith("..") || path.isAbsolute(back)) throw new Error(field + " escapes the repository");
  return absolute;
}

async function rejectLinks(root, value, allowMissingLeaf = false) {
  const relative = repositoryPath(value);
  const parts = relative.split("/");
  let current = root;
  for (let index = 0; index < parts.length; index += 1) {
    current = path.join(current, parts[index]);
    try {
      const info = await lstat(current);
      if (info.isSymbolicLink()) throw new Error("Symbolic links are unsupported: " + value);
    } catch (error) {
      if (allowMissingLeaf && index === parts.length - 1 && error && error.code === "ENOENT") return current;
      throw error;
    }
  }
  return current;
}

function exactKeys(value, keys, field) {
  if (!value || typeof value !== "object" || Array.isArray(value)) throw new Error(field + " must be an object");
  const actual = Object.keys(value).sort();
  const expected = [...keys].sort();
  if (actual.length !== expected.length || actual.some((key, index) => key !== expected[index])) throw new Error(field + " has unexpected or missing fields");
}

function finiteNonNegative(value, field) {
  if (!Number.isFinite(value) || value < 0) throw new Error(field + " must be finite and non-negative");
  return value;
}

function validateHost(host) {
  exactKeys(host, ["arch", "id", "platform", "rust_triple"], "target.host");
  if (host.platform !== process.platform || host.arch !== process.arch || host.id !== process.platform + "-" + process.arch) throw new Error("Configured target is not host-native");
  if (typeof host.rust_triple !== "string" || !host.rust_triple) throw new Error("Invalid Rust host triple");
}

function validateSource(source) {
  exactKeys(source, ["path", "role", "sha256"], "source");
  repositoryPath(source.path, "source.path");
  if (!SOURCE_ROLES.has(source.role)) throw new Error("Unknown evidence role: " + String(source.role));
  if (!HASH.test(source.sha256)) throw new Error("Invalid evidence digest: " + source.path);
}

function validateTarget(target) {
  exactKeys(target, ["artifact_root", "cargo_manifest", "cli_bin", "cli_package", "cli_version", "host", "identifier", "package_manifest", "package_root", "product_name", "prune", "required_roles", "resources", "sidecars", "source_paths", "target_id", "tauri_config"], "target");
  for (const field of ["artifact_root", "cargo_manifest", "cli_bin", "cli_package", "package_manifest", "tauri_config"]) repositoryPath(target[field], "target." + field);
  if (target.package_root !== ".") repositoryPath(target.package_root, "target.package_root");
  if (typeof target.target_id !== "string" || !/^tauri-[a-f0-9-]+$/.test(target.target_id)) throw new Error("Invalid target ID");
  if (typeof target.cli_version !== "string" || !/^2(?:\.|$)/.test(target.cli_version)) throw new Error("Installed CLI is not v2");
  validateHost(target.host);
  if (!Array.isArray(target.source_paths) || !Array.isArray(target.resources) || !Array.isArray(target.sidecars) || !Array.isArray(target.prune) || !Array.isArray(target.required_roles)) throw new Error("Invalid target collections");
  for (const value of target.source_paths) repositoryPath(value, "target.source_paths");
  for (const resource of target.resources) {
    exactKeys(resource, ["kind", "source", "target"], "resource");
    repositoryPath(resource.source, "resource.source");
    repositoryPath(resource.target, "resource.target");
    if (!new Set(["file", "directory"]).has(resource.kind)) throw new Error("Invalid resource kind");
  }
  for (const sidecar of target.sidecars) {
    exactKeys(sidecar, ["configured_source", "source"], "sidecar");
    repositoryPath(sidecar.configured_source, "sidecar.configured_source");
    repositoryPath(sidecar.source, "sidecar.source");
  }
  for (const prune of target.prune) repositoryPath(prune, "target.prune");
  for (const role of target.required_roles) {
    exactKeys(role, ["directly_runnable", "minimum", "role"], "required role");
    if (!ROLES.has(role.role) || !Number.isSafeInteger(role.minimum) || role.minimum < 0 || typeof role.directly_runnable !== "boolean") throw new Error("Invalid required artifact role");
  }
}

function validateCalibration(calibration, evidenceSha256) {
  if (calibration === null) return;
  exactKeys(calibration, ["absolute_growth_bytes", "baseline_total_bytes", "evidence_sha256", "maximum_file_bytes", "maximum_total_bytes", "percentage_growth", "required_paths", "role_counts", "role_maximum_bytes"], "calibration");
  if (calibration.evidence_sha256 !== evidenceSha256) throw new Error("Calibration is stale for current evidence");
  for (const field of ["absolute_growth_bytes", "baseline_total_bytes", "maximum_file_bytes", "maximum_total_bytes", "percentage_growth"]) finiteNonNegative(calibration[field], "calibration." + field);
  exactKeys(calibration.role_counts, ["app", "bundle"], "calibration.role_counts");
  exactKeys(calibration.role_maximum_bytes, ["app", "bundle"], "calibration.role_maximum_bytes");
  for (const role of ROLES) {
    if (!Number.isSafeInteger(calibration.role_counts[role]) || calibration.role_counts[role] < 0) throw new Error("Invalid calibrated role count");
    finiteNonNegative(calibration.role_maximum_bytes[role], "calibration role maximum");
  }
  if (!Array.isArray(calibration.required_paths)) throw new Error("Invalid calibrated required paths");
  calibration.required_paths.forEach((item) => repositoryPath(item, "calibration.required_paths"));
}

export function validateConfig(config) {
  exactKeys(config, ["calibration", "evidence_sha256", "ownership", "schema_version", "sources", "target", "template_version"], "config");
  if (config.schema_version !== 1 || config.template_version !== 1) throw new Error("Unsupported generated configuration version");
  if (typeof config.ownership !== "string" || !MARKER.test(config.ownership)) throw new Error("Invalid configuration ownership marker");
  if (!HASH.test(config.evidence_sha256)) throw new Error("Invalid evidence digest");
  if (!Array.isArray(config.sources) || !config.sources.length) throw new Error("Configuration has no evidence sources");
  config.sources.forEach(validateSource);
  const paths = config.sources.map((source) => source.path);
  if (new Set(paths.map((item) => item.toLocaleLowerCase("en-US"))).size !== paths.length) throw new Error("Evidence paths collide by case");
  if (paths.some((item, index) => index && compareText(paths[index - 1], item) > 0)) throw new Error("Evidence sources are not sorted");
  validateTarget(config.target);
  validateCalibration(config.calibration, config.evidence_sha256);
  return config;
}

async function validateGeneratedFile(root, repositoryPath) {
  const absolute = await rejectLinks(root, repositoryPath);
  const info = await stat(absolute);
  if (!info.isFile()) throw new Error("Generated support path is not a file: " + repositoryPath);
  const content = await readFile(absolute, "utf8");
  const marker = MARKER.exec(content);
  if (!marker || Number(marker[1]) !== 1) throw new Error("Unknown or outdated generated marker: " + repositoryPath);
  if (normalizedDigest(content) !== marker[3]) throw new Error("Generated content digest mismatch: " + repositoryPath);
  return content;
}

async function validateEvidence(root, config) {
  for (const source of config.sources) {
    let absolute;
    if (source.role === "tauri-cli-package" || source.role === "tauri-cli-bin") {
      absolute = resolveRepository(root, source.path, "source.path");
      const canonical = await realpath(absolute);
      const relative = path.relative(root, canonical);
      if (relative.startsWith("..") || path.isAbsolute(relative)) throw new Error("Installed CLI escapes the repository: " + source.path);
    } else absolute = await rejectLinks(root, source.path);
    const info = await stat(absolute);
    if (!info.isFile()) throw new Error("Evidence source is not a file: " + source.path);
    if (sha256(await readFile(absolute)) !== source.sha256) throw new Error("Repository evidence is stale: " + source.path);
  }
  const sourcePaths = new Set(config.sources.map((source) => source.path));
  for (const required of config.target.source_paths) if (!sourcePaths.has(required)) throw new Error("Target source lacks evidence: " + required);
  for (const resource of config.target.resources) {
    const absolute = await rejectLinks(root, resource.source);
    const info = await stat(absolute);
    if (resource.kind === "file" && !info.isFile()) throw new Error("Resource changed type: " + resource.source);
    if (resource.kind === "directory") {
      if (!info.isDirectory()) throw new Error("Resource changed type: " + resource.source);
      const files = await walkFiles(absolute);
      const prefix = resource.source + "/";
      const expected = config.sources.filter((source) => source.role === "resource" && source.path.startsWith(prefix)).map((source) => source.path).sort();
      const actual = files.map((file) => resource.source + "/" + file.relative).sort();
      if (stable(actual) !== stable(expected)) throw new Error("Resource directory contents changed: " + resource.source);
    }
  }
}

export async function loadAndValidate(root = process.cwd()) {
  root = await realpath(path.resolve(root));
  const contents = new Map();
  for (const repositoryPath of SUPPORT_PATHS) contents.set(repositoryPath, await validateGeneratedFile(root, repositoryPath));
  const source = contents.get(CONFIG_PATH);
  let config;
  try { config = JSON.parse(source); } catch (error) { throw new Error("Invalid generated configuration JSON", { cause: error }); }
  validateConfig(config);
  if (canonical(config) !== source) throw new Error("Generated configuration is not canonical");
  await validateEvidence(root, config);
  return config;
}

async function walkFiles(root) {
  const files = [];
  const visit = async (directory, prefix = "") => {
    const entries = await readdir(directory, { withFileTypes: true });
    entries.sort((left, right) => compareText(left.name, right.name));
    for (const entry of entries) {
      const relative = prefix ? prefix + "/" + entry.name : entry.name;
      const absolute = path.join(directory, entry.name);
      if (entry.isSymbolicLink()) throw new Error("Symbolic links are unsupported in artifacts: " + relative);
      if (entry.isDirectory()) await visit(absolute, relative);
      else if (entry.isFile()) files.push({ absolute, relative, info: await stat(absolute) });
      else throw new Error("Unsupported artifact entry: " + relative);
    }
  };
  await visit(root);
  return files;
}

function isDirectApp(relative, info, platform) {
  const parts = relative.split("/");
  if (platform === "win32") return parts.length === 2 && parts[0] === "release" && /\.exe$/i.test(parts[1]);
  if (platform === "darwin") return relative.includes("/bundle/macos/") && relative.includes(".app/Contents/MacOS/");
  return parts.length === 2 && parts[0] === "release" && !path.posix.extname(relative) && (info.mode & 0o111) !== 0;
}

export async function inventoryRun(runDirectory, platform = process.platform) {
  const release = path.join(runDirectory, "release");
  let files;
  try { files = await walkFiles(release); } catch (error) {
    if (error && error.code === "ENOENT") throw new Error("Build produced no release directory in the empty workspace");
    throw error;
  }
  const records = [];
  for (const file of files) {
    const relative = "release/" + file.relative;
    const app = isDirectApp(relative, file.info, platform);
    const bundle = relative.startsWith("release/bundle/");
    if (!app && !bundle) continue;
    records.push({ path: relative, role: app ? "app" : "bundle", size: file.info.size, sha256: sha256(await readFile(file.absolute)), directly_runnable: app });
  }
  records.sort((left, right) => compareText(left.path, right.path));
  if (!records.length) throw new Error("Build produced no fresh distributable artifacts");
  return records;
}

async function ensureSafeDirectory(root, repositoryDirectory) {
  const relative = repositoryPath(repositoryDirectory, "mutable root");
  let current = root;
  for (const segment of relative.split("/")) {
    current = path.join(current, segment);
    try {
      const info = await lstat(current);
      if (info.isSymbolicLink() || !info.isDirectory()) throw new Error("Unsafe mutable-root ancestor: " + repositoryDirectory);
    } catch (error) {
      if (!error || error.code !== "ENOENT") throw error;
      await mkdir(current);
      const info = await lstat(current);
      if (info.isSymbolicLink() || !info.isDirectory()) throw new Error("Unsafe mutable-root ancestor: " + repositoryDirectory);
    }
  }
  return current;
}

async function makeOwnedDirectory(parent, prefix, targetId) {
  const directory = path.join(parent, prefix + "-" + randomUUID());
  await mkdir(directory, { recursive: false });
  await writeFile(path.join(directory, OWNER_FILE), canonical({ kind: "ggcoder-tauri-package", target_id: targetId }), { flag: "wx" });
  return directory;
}

async function assertOwned(directory, targetId) {
  const value = JSON.parse(await readFile(path.join(directory, OWNER_FILE), "utf8"));
  if (value.kind !== "ggcoder-tauri-package" || value.target_id !== targetId) throw new Error("Refusing to mutate an unowned artifact directory");
}

export async function runBuild(root, config, runDirectory, spawnImpl = spawn) {
  const cli = resolveRepository(root, config.target.cli_bin, "target.cli_bin");
  const cwd = config.target.package_root === "." ? root : resolveRepository(root, config.target.package_root, "target.package_root");
  const argv = [cli, "build"];
  await new Promise((resolve, reject) => {
    const child = spawnImpl(process.execPath, argv, {
      cwd,
      env: { ...process.env, CARGO_TARGET_DIR: runDirectory },
      shell: false,
      stdio: "inherit",
      windowsHide: true,
    });
    child.once("error", reject);
    child.once("exit", (code, signal) => code === 0 ? resolve() : reject(new Error("Tauri build failed (code=" + String(code) + ", signal=" + String(signal) + ")")));
  });
  return { executable: process.execPath, argv, cwd, cargoTargetDirectory: runDirectory };
}

async function stageArtifacts(runDirectory, stagingDirectory, records, prune) {
  const retained = records.filter((record) => !prune.some((entry) => record.path === entry || record.path.startsWith(entry + "/")));
  const staged = [];
  for (const record of retained) {
    const source = path.join(runDirectory, ...record.path.split("/"));
    const destination = path.join(stagingDirectory, ...record.path.split("/"));
    const mode = (await stat(source)).mode;
    const bytes = await readFile(source);
    await mkdir(path.dirname(destination), { recursive: true });
    await writeFile(destination, bytes, { flag: "wx", mode });
    staged.push({ ...record, size: bytes.length, sha256: createHash("sha256").update(bytes).digest("hex") });
  }
  if (!staged.length) throw new Error("Pruning removed every distributable artifact");
  return staged;
}

function roleValues(records, role) {
  return records.filter((record) => record.role === role);
}

export function enforceArtifactGates(records, target, calibration) {
  const total = records.reduce((sum, record) => sum + record.size, 0);
  for (const requirement of target.required_roles) {
    if (roleValues(records, requirement.role).length < requirement.minimum) throw new Error("Missing required artifact role: " + requirement.role);
    if (requirement.directly_runnable && !roleValues(records, requirement.role).some((record) => record.directly_runnable)) throw new Error("No directly runnable artifact for role: " + requirement.role);
  }
  if (!calibration) return { total };
  if (records.some((record) => record.size > calibration.maximum_file_bytes)) throw new Error("Artifact exceeds calibrated per-file size gate");
  if (total > calibration.maximum_total_bytes) throw new Error("Artifacts exceed calibrated total size gate");
  for (const role of ROLES) {
    const values = roleValues(records, role);
    if (values.length !== calibration.role_counts[role]) throw new Error("Artifact count changed for role: " + role);
    if (values.reduce((sum, record) => sum + record.size, 0) > calibration.role_maximum_bytes[role]) throw new Error("Artifact role exceeds calibrated size gate: " + role);
  }
  const paths = new Set(records.map((record) => record.path));
  for (const required of calibration.required_paths) if (!paths.has(required)) throw new Error("Calibrated artifact is missing: " + required);
  return { total };
}

function calibrationFor(records, evidenceSha256) {
  const total = records.reduce((sum, record) => sum + record.size, 0);
  const largest = Math.max(...records.map((record) => record.size));
  const absolute = Math.max(16 * 1024 * 1024, Math.ceil(total * 0.2));
  const percentage = 0.2;
  const roleMaximum = (role) => {
    const baseline = roleValues(records, role).reduce((sum, record) => sum + record.size, 0);
    return baseline + Math.max(4 * 1024 * 1024, Math.ceil(baseline * percentage));
  };
  return {
    evidence_sha256: evidenceSha256,
    baseline_total_bytes: total,
    maximum_total_bytes: total + absolute,
    maximum_file_bytes: largest + Math.max(4 * 1024 * 1024, Math.ceil(largest * percentage)),
    role_counts: { app: roleValues(records, "app").length, bundle: roleValues(records, "bundle").length },
    role_maximum_bytes: { app: roleMaximum("app"), bundle: roleMaximum("bundle") },
    required_paths: records.map((record) => record.path).sort(),
    absolute_growth_bytes: absolute,
    percentage_growth: percentage,
  };
}

async function writeManifest(stagingDirectory, records) {
  const manifest = [];
  for (const record of records) {
    const absolute = path.join(stagingDirectory, ...record.path.split("/"));
    manifest.push({ path: record.path, role: record.role, size: (await stat(absolute)).size, sha256: sha256(await readFile(absolute)) });
  }
  manifest.sort((left, right) => compareText(left.path, right.path));
  await writeFile(path.join(stagingDirectory, "manifest.sha256.json"), canonical({ artifacts: manifest }), { flag: "wx" });
  return manifest;
}

async function snapshotStaging(stagingDirectory) {
  const files = await walkFiles(stagingDirectory);
  return Promise.all(files.map(async (file) => ({ path: file.relative, size: file.info.size, sha256: sha256(await readFile(file.absolute)) })));
}

async function assertUnchangedAfterSmoke(stagingDirectory, before) {
  const after = await snapshotStaging(stagingDirectory);
  if (stable(after) !== stable(before)) throw new Error("Smoke test mutated staged output");
}

async function smokeStaged(stagingDirectory, records, smoke = smokeExecutable) {
  const executable = records.find((record) => record.directly_runnable);
  if (!executable) throw new Error("No directly runnable artifact can be smoked");
  const isolated = await makeOwnedDirectory(os.tmpdir(), "gg-tauri-smoke", "smoke");
  try {
    const env = { ...process.env, HOME: isolated, USERPROFILE: isolated, XDG_CONFIG_HOME: path.join(isolated, "config"), XDG_CACHE_HOME: path.join(isolated, "cache"), XDG_DATA_HOME: path.join(isolated, "data"), TEMP: isolated, TMP: isolated, TMPDIR: isolated };
    await smoke(path.join(stagingDirectory, ...executable.path.split("/")), { env, timeoutMs: 15_000 });
  } finally {
    await assertOwned(isolated, "smoke");
    await rm(isolated, { recursive: true, force: true, maxRetries: 10, retryDelay: 100 });
  }
}

async function promote(stagingDirectory, destination, targetId, renameImpl = rename) {
  const parent = path.dirname(destination);
  const backup = path.join(parent, ".gg-tauri-backup-" + targetId + "-" + randomUUID());
  let hadDestination = false;
  try {
    await stat(destination);
    hadDestination = true;
    await assertOwned(destination, targetId);
    await renameImpl(destination, backup);
  } catch (error) {
    if (!error || error.code !== "ENOENT") throw error;
  }
  try {
    await renameImpl(stagingDirectory, destination);
  } catch (error) {
    if (hadDestination) await renameImpl(backup, destination);
    throw error;
  }
  if (hadDestination) await rm(backup, { recursive: true, force: true });
}

async function rewriteCalibration(root, config, calibration, renameImpl = rename) {
  const next = { ...config, calibration };
  next.ownership = next.ownership.replace(/content_sha256=[a-f0-9]{64}/, "content_sha256=" + DIGEST_SENTINEL);
  const provisional = canonical(next);
  const digest = normalizedDigest(provisional);
  const bytes = provisional.replace(DIGEST_SENTINEL, digest);
  validateConfig(JSON.parse(bytes));
  const absolute = resolveRepository(root, CONFIG_PATH, "config path");
  const previous = await readFile(absolute);
  const temporary = absolute + ".calibrate-" + randomUUID() + ".tmp";
  const rollback = absolute + ".rollback-" + randomUUID() + ".tmp";
  let replaced = false;
  try {
    await writeFile(temporary, bytes, { flag: "wx" });
    await renameImpl(temporary, absolute);
    replaced = true;
    const persisted = await loadAndValidate(root);
    if (!persisted.calibration || stable(persisted.calibration) !== stable(calibration)) throw new Error("Persisted calibration does not match the measured baseline");
    return persisted.calibration;
  } catch (error) {
    if (replaced) {
      try {
        await writeFile(rollback, previous, { flag: "wx" });
        await renameImpl(rollback, absolute);
      } catch (rollbackError) {
        throw new Error("Calibration rollback failed: " + (rollbackError instanceof Error ? rollbackError.message : String(rollbackError)), { cause: new AggregateError([error, rollbackError]) });
      }
    }
    throw error;
  } finally {
    await rm(temporary, { force: true });
    await rm(rollback, { force: true });
  }
}

async function cleanupOwnedDirectory(directory, targetId) {
  try {
    await stat(directory);
  } catch (error) {
    if (error && error.code === "ENOENT") return null;
    return error;
  }
  try {
    await assertOwned(directory, targetId);
    await rm(directory, { recursive: true, force: true });
    return null;
  } catch (error) {
    return error;
  }
}

export async function packageTauri({ root = process.cwd(), targetId, calibrate = false, verify = false, spawnImpl = spawn, smoke = smokeExecutable, renameImpl = rename } = {}) {
  root = await realpath(path.resolve(root));
  const config = await loadAndValidate(root);
  if (targetId !== config.target.target_id) throw new Error("Target ID is not configured: " + String(targetId));
  if (verify) return { action: "verify", target_id: targetId, verified: true };
  if (!calibrate && !config.calibration) throw new Error("Packaging requires successful calibration first");
  if (!calibrate && config.calibration.evidence_sha256 !== config.evidence_sha256) throw new Error("Calibration is stale");

  const destination = resolveRepository(root, config.target.artifact_root, "target.artifact_root");
  const parent = await ensureSafeDirectory(root, path.posix.dirname(config.target.artifact_root));
  const runDirectory = await makeOwnedDirectory(parent, ".gg-tauri-work-" + targetId, targetId);
  const stagingDirectory = await makeOwnedDirectory(parent, ".gg-tauri-stage-" + targetId, targetId);
  try {
    const launch = await runBuild(root, config, runDirectory, spawnImpl);
    const inventory = await inventoryRun(runDirectory, config.target.host.platform);
    const records = await stageArtifacts(runDirectory, stagingDirectory, inventory, config.target.prune);
    enforceArtifactGates(records, config.target, calibrate ? null : config.calibration);
    const manifest = await writeManifest(stagingDirectory, records);
    const beforeSmoke = await snapshotStaging(stagingDirectory);
    await smokeStaged(stagingDirectory, records, smoke);
    await assertUnchangedAfterSmoke(stagingDirectory, beforeSmoke);
    const calibration = calibrate ? calibrationFor(records, config.evidence_sha256) : config.calibration;
    await assertOwned(runDirectory, targetId);
    await rm(runDirectory, { recursive: true, force: true });
    if (calibrate) {
      await assertOwned(stagingDirectory, targetId);
      await rm(stagingDirectory, { recursive: true, force: true });
      const persistedCalibration = await rewriteCalibration(root, config, calibration, renameImpl);
      return { action: "calibrate", target_id: targetId, baseline_artifacts: manifest, calibration: persistedCalibration, launch };
    }
    await promote(stagingDirectory, destination, targetId, renameImpl);
    return { action: "package", target_id: targetId, artifact_root: config.target.artifact_root, artifacts: manifest, calibration, launch };
  } catch (error) {
    const cleanupErrors = (await Promise.all([
      cleanupOwnedDirectory(runDirectory, targetId),
      cleanupOwnedDirectory(stagingDirectory, targetId),
    ])).filter((cleanupError) => cleanupError !== null);
    if (cleanupErrors.length) {
      throw new Error("Packaging failed and owned workspace cleanup failed: " + cleanupErrors.map((cleanupError) => cleanupError instanceof Error ? cleanupError.message : String(cleanupError)).join("; "), { cause: new AggregateError([error, ...cleanupErrors]) });
    }
    throw error;
  }
}

export async function main(args = process.argv.slice(2), root = process.cwd()) {
  const parsed = parsePackageArguments(args);
  const result = await packageTauri({ root, targetId: parsed.target, calibrate: parsed.calibrate, verify: parsed.verify });
  process.stdout.write(JSON.stringify(result, null, 2) + "\n");
  return result;
}

if (process.argv[1] && fileURLToPath(import.meta.url) === path.resolve(process.argv[1])) {
  main().catch((error) => { console.error(error instanceof Error ? error.message : String(error)); process.exitCode = 1; });
}
`;
